server:
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/zipkin/
  tracing:
    sampling:
      probability: 1.0