server:
  port: ${PORT:8081}

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


eureka:
  instance:
    hostname: office-service-c6fb3cf8fb5b.herokuapp.com
    non-secure-port: 80
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka/
