server:
  port: ${PORT:8082}

eureka:
  instance:
    hostname: employee-service-4d24719603df.herokuapp.com
    securePortEnabled: true
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka
      non-secure-port: 80
      secure-port: 443

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
