server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0