server:
  port: ${PORT:8082}

eureka:
  instance:
    hostname: employee-service-4d24719603df.herokuapp.com
    non-secure-port-enabled: false
    secure-port-enabled: flase
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
