server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
